// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/postgresql/querier.go
//
// Generated by this command:
//
//	mockgen -source=./internal/repository/postgresql/querier.go -destination=tests/mocks/./repository/postgresql/querier.go
//

// Package mock_postgresql is a generated GoMock package.
package mock_postgresql

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	postgresql "github.com/agungcandra/snap/internal/repository/postgresql"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// FindLatestClientKeyByName mocks base method.
func (m *MockQuerier) FindLatestClientKeyByName(ctx context.Context, name string) (postgresql.ClientKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestClientKeyByName", ctx, name)
	ret0, _ := ret[0].(postgresql.ClientKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestClientKeyByName indicates an expected call of FindLatestClientKeyByName.
func (mr *MockQuerierMockRecorder) FindLatestClientKeyByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestClientKeyByName", reflect.TypeOf((*MockQuerier)(nil).FindLatestClientKeyByName), ctx, name)
}

// FindLatestKeyStorageByName mocks base method.
func (m *MockQuerier) FindLatestKeyStorageByName(ctx context.Context, name string) (postgresql.KeyStorage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestKeyStorageByName", ctx, name)
	ret0, _ := ret[0].(postgresql.KeyStorage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestKeyStorageByName indicates an expected call of FindLatestKeyStorageByName.
func (mr *MockQuerierMockRecorder) FindLatestKeyStorageByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestKeyStorageByName", reflect.TypeOf((*MockQuerier)(nil).FindLatestKeyStorageByName), ctx, name)
}

// InsertClient mocks base method.
func (m *MockQuerier) InsertClient(ctx context.Context, arg postgresql.InsertClientParams) (postgresql.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertClient", ctx, arg)
	ret0, _ := ret[0].(postgresql.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertClient indicates an expected call of InsertClient.
func (mr *MockQuerierMockRecorder) InsertClient(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertClient", reflect.TypeOf((*MockQuerier)(nil).InsertClient), ctx, arg)
}

// InsertClientKey mocks base method.
func (m *MockQuerier) InsertClientKey(ctx context.Context, arg postgresql.InsertClientKeyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertClientKey", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertClientKey indicates an expected call of InsertClientKey.
func (mr *MockQuerierMockRecorder) InsertClientKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertClientKey", reflect.TypeOf((*MockQuerier)(nil).InsertClientKey), ctx, arg)
}

// InsertKeyStorage mocks base method.
func (m *MockQuerier) InsertKeyStorage(ctx context.Context, arg postgresql.InsertKeyStorageParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertKeyStorage", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertKeyStorage indicates an expected call of InsertKeyStorage.
func (mr *MockQuerierMockRecorder) InsertKeyStorage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertKeyStorage", reflect.TypeOf((*MockQuerier)(nil).InsertKeyStorage), ctx, arg)
}
