BEGIN;

CREATE TABLE clients (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    public_key BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
