// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: clients.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertClient = `-- name: InsertClient :one
INSERT INTO clients(id, name) VALUES ($1, $2) RETURNING id, name, created_at, updated_at
`

type InsertClientParams struct {
	ID   pgtype.UUID `db:"id"`
	Name string      `db:"name"`
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, insertClient, arg.ID, arg.Name)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
