// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: keys.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertKey = `-- name: InsertKey :one
INSERT INTO keys(client_id, encrypted_key) VALUES ($1, $2) RETURNING id
`

type InsertKeyParams struct {
	ClientID     pgtype.UUID `db:"client_id"`
	EncryptedKey []byte      `db:"encrypted_key"`
}

func (q *Queries) InsertKey(ctx context.Context, arg InsertKeyParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertKey, arg.ClientID, arg.EncryptedKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}
