// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID        pgtype.UUID      `db:"id"`
	Name      string           `db:"name"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

type Key struct {
	ID           int64            `db:"id"`
	ClientID     pgtype.UUID      `db:"client_id"`
	EncryptedKey []byte           `db:"encrypted_key"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
}

type Nonce struct {
	KeyID     int64            `db:"key_id"`
	Nonce     []byte           `db:"nonce"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
}

type Salt struct {
	KeyID     int64            `db:"key_id"`
	Salt      []byte           `db:"salt"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
}
