// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID        pgtype.UUID      `db:"id"`
	Name      string           `db:"name"`
	PublicKey []byte           `db:"public_key"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

type ClientKey struct {
	ID        int64            `db:"id"`
	Name      string           `db:"name"`
	Version   int32            `db:"version"`
	Data      []byte           `db:"data"`
	Nonce     []byte           `db:"nonce"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
}

type KeyStorage struct {
	ID        int64            `db:"id"`
	Name      string           `db:"name"`
	Version   int32            `db:"version"`
	Data      []byte           `db:"data"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
}
