// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: nonces.sql

package postgresql

import (
	"context"
)

const insertNonce = `-- name: InsertNonce :exec
INSERT INTO nonces(key_id, nonce) VALUES ($1, $2)
`

type InsertNonceParams struct {
	KeyID int64  `db:"key_id"`
	Nonce []byte `db:"nonce"`
}

func (q *Queries) InsertNonce(ctx context.Context, arg InsertNonceParams) error {
	_, err := q.db.Exec(ctx, insertNonce, arg.KeyID, arg.Nonce)
	return err
}
