// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package postgresql

import (
	"context"
)

type Querier interface {
	InsertClient(ctx context.Context, arg InsertClientParams) (Client, error)
	InsertKey(ctx context.Context, arg InsertKeyParams) (int64, error)
	InsertNonce(ctx context.Context, arg InsertNonceParams) error
	InsertSalt(ctx context.Context, arg InsertSaltParams) error
}

var _ Querier = (*Queries)(nil)
