// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: salts.sql

package postgresql

import (
	"context"
)

const insertSalt = `-- name: InsertSalt :exec
INSERT INTO salts(key_id, salt) VALUES ($1, $2)
`

type InsertSaltParams struct {
	KeyID int64  `db:"key_id"`
	Salt  []byte `db:"salt"`
}

func (q *Queries) InsertSalt(ctx context.Context, arg InsertSaltParams) error {
	_, err := q.db.Exec(ctx, insertSalt, arg.KeyID, arg.Salt)
	return err
}
