// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/access_token/base.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/access_token/base.go -destination=tests/mocks/./service/access_token/base.go
//

// Package mock_accesstoken is a generated GoMock package.
package mock_accesstoken

import (
	gomock "go.uber.org/mock/gomock"
)

// MockaccessTokenRepository is a mock of accessTokenRepository interface.
type MockaccessTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockaccessTokenRepositoryMockRecorder
}

// MockaccessTokenRepositoryMockRecorder is the mock recorder for MockaccessTokenRepository.
type MockaccessTokenRepositoryMockRecorder struct {
	mock *MockaccessTokenRepository
}

// NewMockaccessTokenRepository creates a new mock instance.
func NewMockaccessTokenRepository(ctrl *gomock.Controller) *MockaccessTokenRepository {
	mock := &MockaccessTokenRepository{ctrl: ctrl}
	mock.recorder = &MockaccessTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccessTokenRepository) EXPECT() *MockaccessTokenRepositoryMockRecorder {
	return m.recorder
}
